const CATS = {
  italian:   {label:"Italian",          color:"#7f8a52"},
  steakhouse:{label:"Steakhouse",       color:"#a4592e"},
  seafood:   {label:"Seafood",          color:"#3f7d8a"},
  comfort:   {label:"Comfort & Healthy",color:"#9a7d3c"},
  mealprep:  {label:"Meal Prep",        color:"#5d8a6a"}
};
const COURSES = { appetizer:"Appetizers", main:"Main Courses", side:"Sides", dessert:"Desserts" };

const RECIPES = [
  /* ===== APPETIZERS ===== */
  {course:"appetizer",cat:"seafood",emoji:"🧈",title:"Seared Scallops & Pea Purée",it:"A restaurant-style starter",time:"25 min",serves:"2",level:"Medium",
   desc:"Golden-crusted scallops over a silky pea purée with lemon butter.",
   ing:["6 large sea scallops","1.5 cups peas","2 tbsp cream","3 tbsp butter","1 tbsp olive oil","1/2 lemon","Salt, pepper, mint"],
   steps:["Boil peas 3 min; blend with cream, 1 tbsp butter, salt and pepper until smooth.","Pat scallops very dry and season. Sear in hot oil 1.5–2 min per side until golden.","Add butter and a squeeze of lemon; baste briefly.","Spoon purée onto plates, top with scallops and the lemon butter; garnish with mint."],
   pair:"A Chablis or sparkling wine."},
  {course:"appetizer",cat:"italian",emoji:"🥗",title:"Tomato & White Bean Salad",it:"Insalata di fagioli",time:"10 min",serves:"2",level:"Easy",
   desc:"Cannellini beans, juicy tomatoes and arugula in a bright lemon-olive oil dressing.",
   ing:["1 can cannellini beans, rinsed","2 cups cherry tomatoes, halved","2 cups arugula","2 tbsp olive oil","1 tbsp lemon juice","2 tbsp shaved Parmesan","Salt, pepper, basil"],
   steps:["Stir beans, tomatoes, olive oil and lemon juice together.","Fold in arugula; season with salt and pepper.","Top with Parmesan and torn basil and serve."],
   pair:"A crisp Vermentino."},
  {course:"appetizer",cat:"italian",emoji:"🍅",title:"Bruschetta al Pomodoro",it:"Toasted bread, tomato & basil",time:"15 min",serves:"2",level:"Easy",
   desc:"Crisp grilled bread piled with garlicky marinated tomatoes and basil.",
   ing:["4 slices crusty bread","2 cups tomatoes, diced","1 clove garlic","2 tbsp olive oil","Fresh basil","Salt, pepper, balsamic"],
   steps:["Toss tomatoes with olive oil, salt, pepper and a splash of balsamic; rest 10 min.","Toast or grill the bread; rub with the cut garlic clove.","Spoon tomatoes over the bread, scatter basil, finish with olive oil."],
   pair:"A light Italian white or Prosecco."},
  {course:"appetizer",cat:"seafood",emoji:"🍤",title:"Classic Shrimp Cocktail",it:"Chilled & zesty",time:"15 min",serves:"2",level:"Easy",
   desc:"Poached shrimp with a bright, horseradish-spiked cocktail sauce.",
   ing:["12 large shrimp, peeled","1/2 cup ketchup","1 tbsp prepared horseradish","1 tsp lemon juice","Dash hot sauce","Lemon wedges","Salt"],
   steps:["Simmer shrimp in salted water 2–3 min until pink; chill in ice water.","Stir ketchup, horseradish, lemon juice and hot sauce for the sauce.","Serve shrimp around the sauce with lemon wedges."],
   pair:"A dry sparkling wine."},
  {course:"appetizer",cat:"italian",emoji:"🧀",title:"Caprese Salad",it:"Insalata caprese",time:"10 min",serves:"2",level:"Easy",
   desc:"Fresh mozzarella, ripe tomato and basil with olive oil and balsamic.",
   ing:["1 ball fresh mozzarella","2 ripe tomatoes","Fresh basil leaves","2 tbsp olive oil","Balsamic glaze","Flaky salt, pepper"],
   steps:["Slice mozzarella and tomatoes; arrange alternating with basil.","Drizzle with olive oil and balsamic glaze.","Finish with flaky salt and cracked pepper."],
   pair:"A Pinot Grigio."},
  {course:"appetizer",cat:"comfort",emoji:"🫓",title:"Whipped Ricotta Toast",it:"Creamy & light",time:"12 min",serves:"2",level:"Easy",
   desc:"Lemony whipped ricotta on toast with honey, chili and herbs.",
   ing:["3/4 cup ricotta","1 tsp lemon zest","4 slices bread","1 tbsp honey","Pinch chili flakes","Olive oil","Salt, herbs"],
   steps:["Whip ricotta with lemon zest, a little olive oil and salt until smooth.","Toast the bread.","Spread ricotta, drizzle honey, add chili flakes and herbs."],
   pair:"A light sparkling wine."},

  /* ===== MAIN COURSES ===== */
  {course:"main",cat:"italian",emoji:"🍝",title:"Spaghetti Aglio e Olio",it:"Garlic & oil, the Roman way",time:"20 min",serves:"2",level:"Easy",
   desc:"Pantry magic — golden garlic, good olive oil, chili and parsley on al dente spaghetti.",
   ing:["6 oz spaghetti","1/3 cup olive oil","5 cloves garlic, sliced","1/2 tsp chili flakes","1/4 cup parsley","1/2 cup pasta water","Salt, Parmesan"],
   steps:["Boil spaghetti until al dente; reserve 1/2 cup water.","Warm oil over medium-low, add garlic and chili, cook until pale gold.","Add a splash of pasta water; toss in pasta and parsley until silky.","Season, finish with Parmesan, serve."],
   pair:"A crisp Vermentino."},
  {course:"main",cat:"italian",emoji:"🍗",title:"Chicken Parmesan",it:"Pollo alla parmigiana",time:"45 min",serves:"2",level:"Medium",
   desc:"Crisp breaded cutlets under bubbling marinara and melted mozzarella.",
   ing:["2 chicken breasts","1/2 cup flour","2 eggs","1 cup breadcrumbs","1/2 cup Parmesan","1.5 cups marinara","4 oz mozzarella","Olive oil, basil"],
   steps:["Pound chicken thin; dredge in flour, egg, then breadcrumbs + half the Parmesan.","Pan-fry in oil 3–4 min per side until golden.","Top with marinara and cheeses; bake at 425°F 12–15 min.","Finish with basil."],
   pair:"A medium Chianti."},
  {course:"main",cat:"italian",emoji:"🍚",title:"Mushroom Risotto",it:"Risotto ai funghi",time:"40 min",serves:"2",level:"Medium",
   desc:"Creamy, slow-stirred Arborio rice with earthy mushrooms and Parmesan.",
   ing:["1 cup Arborio rice","8 oz mushrooms","1 shallot","4 cups warm stock","1/2 cup white wine","3 tbsp butter","1/3 cup Parmesan, parsley"],
   steps:["Brown mushrooms; set aside.","Soften shallot in butter, toast rice 1 min, add wine.","Add warm stock a ladle at a time, stirring ~18 min until creamy.","Fold in mushrooms, Parmesan and butter; season."],
   pair:"A light Pinot Noir."},
  {course:"main",cat:"italian",emoji:"🍅",title:"Penne alla Vodka",it:"Silky tomato-cream",time:"30 min",serves:"2",level:"Easy",
   desc:"Tomato, a splash of vodka and cream in a luxe blush sauce.",
   ing:["6 oz penne","2 tbsp olive oil","2 cloves garlic","1/2 tsp chili","3 tbsp tomato paste","2 tbsp vodka","1/2 cup cream","1/4 cup Parmesan"],
   steps:["Boil penne until al dente.","Soften garlic and chili in oil, add tomato paste, cook 2 min.","Add vodka 1 min, then cream until smooth.","Toss pasta with sauce, pasta water and Parmesan; finish with basil."],
   pair:"A chilled rosé."},
  {course:"main",cat:"italian",emoji:"🍕",title:"Margherita Flatbread",it:"Quick weeknight pizza",time:"25 min",serves:"2",level:"Easy",
   desc:"Blistered flatbread with tomato, fresh mozzarella and basil.",
   ing:["2 flatbreads","1/2 cup crushed tomatoes","4 oz fresh mozzarella","1 clove garlic","Olive oil, basil","Salt, pepper"],
   steps:["Heat oven to 450°F. Rub flatbreads with garlic and oil.","Spread tomatoes, season, dot with mozzarella.","Bake 8–10 min until crisp; finish with basil and olive oil."],
   pair:"An Italian lager or Chianti."},
  {course:"main",cat:"seafood",emoji:"🍤",title:"Lemon Shrimp Linguine",it:"Linguine ai gamberi",time:"25 min",serves:"2",level:"Easy",
   desc:"Garlicky shrimp, lemon and white wine tangled through fresh linguine.",
   ing:["6 oz linguine","10 shrimp, peeled","3 cloves garlic","3 tbsp butter","1/4 cup white wine","1 lemon","Chili flakes, parsley"],
   steps:["Cook linguine until al dente; reserve water.","Sauté garlic and chili in butter; add shrimp 1–2 min per side.","Add wine and lemon, simmer 1 min.","Toss pasta with zest, parsley and a splash of pasta water."],
   pair:"A crisp Vermentino."},
  {course:"main",cat:"steakhouse",emoji:"🥩",title:"Garlic Butter Ribeye",it:"The classic steakhouse sear",time:"25 min",serves:"2",level:"Medium",
   desc:"A deeply seared ribeye basted in garlic-herb butter — pure steakhouse.",
   ing:["2 ribeye steaks","2 tbsp oil","3 tbsp butter","3 cloves garlic","Thyme & rosemary","Flaky salt, pepper"],
   steps:["Pat steaks dry, season, rest 30 min.","Sear in screaming-hot oil 3 min per side.","Lower heat, add butter, garlic and herbs; baste 1–2 min.","Pull at 130–135°F, rest 8 min, spoon over butter."],
   pair:"A bold Cabernet."},
  {course:"main",cat:"steakhouse",emoji:"🔥",title:"Grilled Sirloin & Asparagus",it:"Bistecca con asparagi",time:"25 min",serves:"2",level:"Easy",
   desc:"Lean rosemary-garlic sirloin and charred asparagus off the grill.",
   ing:["2 top sirloin steaks","1 tbsp olive oil","2 cloves garlic","2 sprigs rosemary","1 bunch asparagus","1/2 lemon","Salt, pepper"],
   steps:["Rub steaks with oil, garlic, salt, pepper.","Grill 3–4 min per side for medium-rare, rosemary on top.","Rest 8 min; grill asparagus 4–5 min.","Squeeze lemon; slice steak across the grain."],
   pair:"A Chianti Classico."},
  {course:"main",cat:"steakhouse",emoji:"🍷",title:"Filet Mignon, Red Wine Sauce",it:"Tender & elegant",time:"35 min",serves:"2",level:"Medium",
   desc:"Butter-basted filet with a glossy red wine pan reduction.",
   ing:["2 filet mignon","2 tbsp oil + 3 tbsp butter","2 cloves garlic","Thyme","1/2 cup red wine","1/2 cup beef stock","Salt, pepper"],
   steps:["Season filets; sear 3 min per side.","Add butter, garlic, thyme; baste, rest 8 min.","Add wine and stock to the pan; reduce by half.","Swirl in butter; spoon over filets."],
   pair:"A Malbec or Bordeaux."},
  {course:"main",cat:"steakhouse",emoji:"🌿",title:"NY Strip with Chimichurri",it:"Bright herb sauce",time:"25 min",serves:"2",level:"Easy",
   desc:"Charred strip steak cut by a punchy garlic-herb chimichurri.",
   ing:["2 NY strip steaks","Olive oil, salt, pepper","1 cup parsley","2 cloves garlic","2 tbsp red wine vinegar","1/3 cup olive oil","Chili, oregano"],
   steps:["Stir chimichurri ingredients together; season.","Sear or grill steaks 3–4 min per side.","Rest 8 min, slice across the grain.","Spoon chimichurri over."],
   pair:"A Malbec."},
  {course:"main",cat:"steakhouse",emoji:"🍖",title:"Steakhouse Pork Chops",it:"With caramelized apples",time:"30 min",serves:"2",level:"Easy",
   desc:"Thick seared chops with sweet-tart skillet apples.",
   ing:["2 bone-in pork chops","2 tbsp oil + 2 tbsp butter","2 cloves garlic","Thyme","1 apple","1 tbsp brown sugar","Salt, pepper"],
   steps:["Season chops; sear 4 min per side.","Add butter, garlic, thyme; baste, then rest.","Cook apple slices with brown sugar until caramelized.","Top chops with the apples."],
   pair:"A fruity Zinfandel."},
  {course:"main",cat:"seafood",emoji:"🐟",title:"Pan-Seared Salmon",it:"Crispy skin, lemon butter",time:"20 min",serves:"2",level:"Easy",
   desc:"Crisp-skinned salmon finished with a quick lemon-butter pan sauce.",
   ing:["2 salmon fillets","1 tbsp oil","2 tbsp butter","1 clove garlic","1/2 lemon","Salt, pepper, dill"],
   steps:["Pat salmon dry, season. Sear skin-side down 4–5 min.","Flip, cook 2–3 min.","Add butter, garlic and lemon; baste.","Finish with dill."],
   pair:"A Chardonnay."},
  {course:"main",cat:"seafood",emoji:"🍤",title:"Shrimp Scampi",it:"Garlic butter & wine",time:"20 min",serves:"2",level:"Easy",
   desc:"Plump shrimp in a garlicky white wine butter — over pasta or with bread.",
   ing:["1 lb shrimp","4 tbsp butter","4 cloves garlic","1/3 cup white wine","1/2 lemon","Chili, parsley"],
   steps:["Sauté garlic and chili in 2 tbsp butter.","Add shrimp 1–2 min per side; remove.","Add wine and lemon, reduce; swirl in butter.","Return shrimp, toss with parsley."],
   pair:"A Sauvignon Blanc."},
  {course:"main",cat:"seafood",emoji:"🌮",title:"Blackened Fish Tacos",it:"With lime slaw",time:"25 min",serves:"2",level:"Easy",
   desc:"Spiced fish in warm tortillas with crunchy lime slaw.",
   ing:["2 white fish fillets","1 tbsp blackening spice","2 cups cabbage","2 tbsp mayo or yogurt","1 lime","6 tortillas","Cilantro, oil"],
   steps:["Toss cabbage with mayo, lime, cilantro, salt.","Coat fish in spice; sear 3 min per side.","Warm tortillas.","Flake fish into tortillas, top with slaw and lime."],
   pair:"A lager or margarita."},
  {course:"main",cat:"seafood",emoji:"🍋",title:"Lemon Herb Baked Cod",it:"Light & flaky",time:"25 min",serves:"2",level:"Easy",
   desc:"Tender cod baked with lemon, garlic and herbs — barely any effort.",
   ing:["2 cod fillets","2 tbsp butter, melted","2 cloves garlic","1 lemon","2 tbsp parsley","Salt, paprika"],
   steps:["Heat oven to 400°F.","Mix butter, garlic, lemon and parsley; pour over cod.","Season with salt and paprika.","Bake 12–15 min until flaky; spoon over juices."],
   pair:"A dry Riesling."},
  {course:"main",cat:"seafood",emoji:"🍣",title:"Tuna Poke Bowl",it:"No-cook & fresh",time:"15 min",serves:"2",level:"Easy",
   desc:"Marinated raw tuna over rice with avocado, cucumber and sesame.",
   ing:["8 oz sushi-grade tuna","2 tbsp soy sauce","1 tsp sesame oil","1 tsp rice vinegar","2 cups rice","1 avocado","1/2 cucumber","Sesame, scallion"],
   steps:["Toss tuna with soy, sesame oil and vinegar; chill 10 min.","Divide rice between bowls.","Top with tuna, avocado and cucumber.","Finish with sesame and scallion."],
   pair:"A dry sparkling wine or sake."},
  {course:"main",cat:"comfort",emoji:"🍗",title:"Sheet-Pan Chicken & Veg",it:"One pan, no fuss",time:"40 min",serves:"2",level:"Easy",
   desc:"Juicy chicken thighs roasted with vegetables — dinner on a single tray.",
   ing:["4 chicken thighs","2 cups broccoli & peppers","1 cup baby potatoes","2 tbsp olive oil","2 cloves garlic","Paprika, oregano","1/2 lemon"],
   steps:["Heat oven to 425°F. Toss veg and potatoes in oil, garlic, seasoning.","Nestle in seasoned thighs.","Roast 30–35 min until golden.","Squeeze lemon over."],
   pair:"A light unoaked white."},
  {course:"main",cat:"comfort",emoji:"🌶️",title:"Turkey & White Bean Chili",it:"Lean & cozy",time:"40 min",serves:"3–4",level:"Easy",
   desc:"A lighter chili that's still rich, hearty and freezer-friendly.",
   ing:["1 lb ground turkey","1 onion","2 cloves garlic","1 can white beans","1 can diced tomatoes","2 cups stock","Chili powder, cumin"],
   steps:["Brown turkey with onion and garlic.","Stir in chili powder and cumin.","Add beans, tomatoes and stock; simmer 25 min.","Season and serve with toppings."],
   pair:"A cold lager."},
  {course:"main",cat:"comfort",emoji:"🥗",title:"Greek Chicken Bowls",it:"Bright & balanced",time:"30 min",serves:"2",level:"Easy",
   desc:"Lemon-oregano chicken over rice with cucumber, tomato and tzatziki.",
   ing:["2 chicken breasts","2 tbsp olive oil","1 lemon","1 tsp oregano","2 cups rice or quinoa","1 cucumber, 1 cup tomatoes","Tzatziki, feta"],
   steps:["Toss chicken with oil, lemon, oregano; sear 6–8 min.","Divide grain between bowls.","Top with chicken, cucumber and tomato.","Add tzatziki and feta."],
   pair:"A crisp Assyrtiko."},
  {course:"main",cat:"comfort",emoji:"🍯",title:"Honey Garlic Salmon Bowl",it:"Sweet & savory",time:"25 min",serves:"2",level:"Easy",
   desc:"Glazed salmon over rice and greens — fast, healthy and crave-worthy.",
   ing:["2 salmon fillets, cubed","2 tbsp honey","2 tbsp soy sauce","2 cloves garlic","1 tsp ginger","2 cups rice","Greens, sesame"],
   steps:["Whisk honey, soy, garlic and ginger.","Sear salmon 2 min, add glaze, toss until sticky.","Serve over rice with greens.","Finish with sesame and scallion."],
   pair:"An off-dry Riesling."},
  {course:"main",cat:"comfort",emoji:"🍲",title:"Hearty Minestrone",it:"Garden vegetable soup",time:"40 min",serves:"3–4",level:"Easy",
   desc:"A big pot of vegetables, beans and pasta in a savory tomato broth.",
   ing:["2 tbsp olive oil","1 onion, 2 carrots, 2 celery","2 cloves garlic","1 can tomatoes","4 cups stock","1 can cannellini beans","1/2 cup pasta, basil"],
   steps:["Soften onion, carrot, celery and garlic.","Add tomatoes, stock and Parmesan rind; simmer 15 min.","Add beans and pasta; cook until tender.","Finish with basil and Parmesan."],
   pair:"A light Italian red."},
  {course:"main",cat:"comfort",emoji:"🍋",title:"Roast Lemon Chicken Thighs",it:"Crispy & golden",time:"45 min",serves:"2",level:"Easy",
   desc:"Crispy-skinned thighs roasted with lemon and garlic — weeknight comfort.",
   ing:["4–6 chicken thighs","2 tbsp olive oil","4 cloves garlic","1 lemon, sliced","Rosemary","Salt, pepper"],
   steps:["Heat oven to 425°F; season thighs.","Arrange with garlic, lemon and rosemary; drizzle oil.","Roast 35–40 min until crisp.","Spoon over the pan juices."],
   pair:"A Chardonnay."},

  /* ===== SIDES ===== */
  {course:"side",cat:"steakhouse",emoji:"🥔",title:"Garlic Parmesan Mashed Potatoes",it:"Creamy & rich",time:"30 min",serves:"2–3",level:"Easy",
   desc:"Buttery Yukon Gold mash with roasted garlic and Parmesan.",
   ing:["1.5 lb Yukon Gold potatoes","4 tbsp butter","1/3 cup warm milk","1/3 cup Parmesan","2 cloves garlic","Salt, pepper"],
   steps:["Boil peeled potatoes 18–20 min until tender.","Drain and mash with butter, warm milk and Parmesan.","Stir in softened garlic; season well.","Keep warm until serving."],
   pair:"Pairs with any steak."},
  {course:"side",cat:"comfort",emoji:"🌿",title:"Blistered Asparagus",it:"Charred & bright",time:"12 min",serves:"2",level:"Easy",
   desc:"Asparagus seared until tender-crisp and finished with lemon.",
   ing:["1 bunch asparagus","1 tbsp olive oil","1 clove garlic","1/2 lemon","Salt, pepper, chili flakes"],
   steps:["Toss asparagus in oil, salt and pepper.","Sear in a hot pan 4–5 min, turning, until charred.","Add sliced garlic and chili the last minute.","Squeeze lemon over and serve."],
   pair:"Light and goes with everything."},
  {course:"side",cat:"comfort",emoji:"🥦",title:"Garlic Broccolini",it:"Sautéed & savory",time:"12 min",serves:"2",level:"Easy",
   desc:"Tender broccolini sautéed with garlic and a touch of chili.",
   ing:["1 bunch broccolini","2 tbsp olive oil","2 cloves garlic","Chili flakes","2 tbsp water","Salt, lemon"],
   steps:["Blanch or steam broccolini 2 min.","Sauté in oil with sliced garlic and chili 2–3 min.","Add water to steam briefly; season.","Finish with lemon."],
   pair:"A clean green side for any main."},
  {course:"side",cat:"comfort",emoji:"🌾",title:"Herbed Farro",it:"Nutty whole grain",time:"30 min",serves:"3",level:"Easy",
   desc:"Chewy farro tossed with olive oil, herbs and blistered tomatoes.",
   ing:["3/4 cup farro","1.5 cups stock","1 cup cherry tomatoes","2 tbsp olive oil","Parsley","Salt, pepper"],
   steps:["Simmer farro in stock 25–30 min; drain.","Blister tomatoes in a hot pan 2 min.","Toss farro with oil, tomatoes and parsley.","Season and serve warm."],
   pair:"A hearty grain side."},
  {course:"side",cat:"steakhouse",emoji:"🥔",title:"Crispy Smashed Potatoes",it:"Golden & crunchy",time:"40 min",serves:"2–3",level:"Easy",
   desc:"Boiled baby potatoes smashed and roasted until shatteringly crisp.",
   ing:["1 lb baby potatoes","3 tbsp olive oil","Rosemary","2 cloves garlic","Flaky salt, pepper"],
   steps:["Boil potatoes until tender; drain.","Smash lightly on an oiled sheet pan.","Drizzle with oil, rosemary and garlic.","Roast at 450°F 25 min until crispy; salt well."],
   pair:"Crowd-pleasing with any steak."},
  {course:"side",cat:"comfort",emoji:"🥬",title:"Garlicky Sautéed Spinach",it:"Quick & green",time:"8 min",serves:"2",level:"Easy",
   desc:"A fast skillet of spinach wilted with garlic and olive oil.",
   ing:["10 oz spinach","2 tbsp olive oil","2 cloves garlic","Pinch chili flakes","Salt, lemon"],
   steps:["Warm oil with sliced garlic and chili until fragrant.","Add spinach in batches, tossing until wilted.","Season with salt.","Finish with a squeeze of lemon."],
   pair:"A light, healthy green."},

  /* ===== DESSERTS ===== */
  {course:"dessert",cat:"comfort",emoji:"🍫",title:"Molten Chocolate Lava Cake",it:"Warm flowing center",time:"25 min",serves:"2",level:"Medium",
   desc:"Warm dark-chocolate cakes with a molten center.",
   ing:["4 oz dark chocolate","1/2 cup butter","2 eggs + 2 yolks","1/4 cup sugar","2 tbsp flour","Pinch salt","Powdered sugar"],
   steps:["Butter and flour two ramekins; heat oven to 425°F.","Melt chocolate and butter.","Whisk eggs, yolks and sugar; fold in chocolate, flour and salt.","Bake 12 min until edges set but centers jiggle; invert and dust."],
   pair:"A tawny Port or espresso."},
  {course:"dessert",cat:"comfort",emoji:"🍑",title:"Grilled Peaches & Honey Ricotta",it:"Light & summery",time:"15 min",serves:"2",level:"Easy",
   desc:"Caramelized peaches over whipped honey ricotta with pistachios.",
   ing:["2 ripe peaches","3/4 cup ricotta","1 tbsp honey","1/2 tsp vanilla","2 tbsp pistachios","Mint"],
   steps:["Whip ricotta with honey and vanilla.","Grill or sear peach halves cut-side down 3–4 min.","Spoon ricotta onto plates, top with peaches.","Drizzle honey, scatter pistachios and mint."],
   pair:"A glass of Moscato."},
  {course:"dessert",cat:"italian",emoji:"🍰",title:"Tiramisu",it:"Coffee & mascarpone",time:"25 min + chill",serves:"4",level:"Medium",
   desc:"Espresso-soaked ladyfingers layered with mascarpone cream.",
   ing:["1 cup strong espresso, cooled","16 ladyfingers","1 cup mascarpone","2 egg yolks","1/4 cup sugar","Cocoa powder"],
   steps:["Whisk yolks and sugar until pale; fold in mascarpone.","Dip ladyfingers briefly in espresso.","Layer ladyfingers and cream in a dish.","Chill 2+ hours; dust with cocoa."],
   pair:"An espresso or Vin Santo."},
  {course:"dessert",cat:"italian",emoji:"☕",title:"Affogato",it:"Gelato 'drowned' in espresso",time:"5 min",serves:"2",level:"Easy",
   desc:"A scoop of vanilla gelato drowned in a shot of hot espresso.",
   ing:["2 scoops vanilla gelato","2 shots hot espresso","Optional: shaved chocolate, biscotti"],
   steps:["Place a scoop of gelato in each glass.","Pull two shots of espresso.","Pour the hot espresso over the gelato at the table.","Top with chocolate or serve with biscotti."],
   pair:"A digestivo like amaro."},
  {course:"dessert",cat:"italian",emoji:"🫐",title:"Berries & Mascarpone",it:"Effortless & elegant",time:"10 min",serves:"2",level:"Easy",
   desc:"Sweet mascarpone cream with macerated mixed berries.",
   ing:["1/2 cup mascarpone","2 tbsp powdered sugar","1/2 tsp vanilla","1.5 cups mixed berries","1 tsp sugar","Mint"],
   steps:["Toss berries with sugar; rest 10 min.","Whip mascarpone with powdered sugar and vanilla.","Spoon cream into glasses, top with berries.","Garnish with mint."],
   pair:"A sparkling Moscato."},
  {course:"dessert",cat:"italian",emoji:"🍋",title:"Lemon Olive Oil Cake",it:"Moist & citrusy",time:"45 min",serves:"6",level:"Medium",
   desc:"A tender, fragrant olive oil cake with bright lemon.",
   ing:["1.5 cups flour","3/4 cup sugar","2 eggs","1/2 cup olive oil","1/2 cup milk","2 lemons (zest + juice)","1.5 tsp baking powder, salt"],
   steps:["Heat oven to 350°F; grease a cake pan.","Whisk eggs and sugar, then oil, milk, zest and juice.","Fold in flour, baking powder and salt.","Bake 30–35 min until golden; cool and dust with sugar."],
   pair:"A limoncello or sweet white."},

  /* ===== MEAL PREP (mains, weight loss) ===== */
  {course:"main",cat:"mealprep",emoji:"🍗",title:"Chicken & Rice Prep Bowls",it:"The classic high-protein box",time:"45 min",serves:"4 boxes",level:"Easy",cal:430,protein:"42g",
   desc:"Lean grilled chicken, fluffy rice and roasted broccoli — four grab-and-go boxes.",
   ing:["1.5 lb chicken breast","1.5 cups rice (dry)","4 cups broccoli","2 tbsp olive oil","2 cloves garlic","Paprika, garlic powder","1/2 lemon"],
   steps:["Season and cook chicken to 165°F; slice. Cook rice.","Roast broccoli in oil and garlic at 425°F 18 min.","Divide rice, chicken and broccoli into 4 containers.","Add lemon; cool and refrigerate up to 4 days."],
   pair:"~430 cal · 42g protein"},
  {course:"main",cat:"mealprep",emoji:"🌮",title:"Turkey Taco Prep Bowls",it:"Lean & punchy",time:"35 min",serves:"4 boxes",level:"Easy",cal:410,protein:"38g",
   desc:"Lean turkey taco meat over rice and beans with peppers.",
   ing:["1.25 lb lean ground turkey","1 onion + 2 peppers","1 can black beans","2 tbsp taco seasoning","1.5 cups rice","1 cup corn","Lime, cilantro"],
   steps:["Cook rice. Brown turkey with onion and peppers.","Add seasoning, beans and corn; simmer 5 min.","Divide rice and turkey into 4 boxes.","Top with lime and cilantro; refrigerate up to 4 days."],
   pair:"~410 cal · 38g protein"},
  {course:"main",cat:"mealprep",emoji:"🥚",title:"Egg & Veggie Cups",it:"Grab-and-go breakfast",time:"30 min",serves:"6 cups",level:"Easy",cal:120,protein:"11g",
   desc:"Baked egg muffins loaded with veggies — breakfast solved all week.",
   ing:["8 eggs","1 cup spinach","1/2 cup peppers","1/4 cup onion","1/3 cup feta or cheddar","Salt, pepper"],
   steps:["Heat oven to 375°F; grease a muffin tin.","Whisk eggs with salt and pepper; stir in veg and cheese.","Pour into 6 cups.","Bake 18–20 min; cool and refrigerate up to 4 days."],
   pair:"~120 cal each · 11g protein"},
  {course:"main",cat:"mealprep",emoji:"🐟",title:"Salmon & Quinoa Boxes",it:"Omega-3 powerhouse",time:"35 min",serves:"3 boxes",level:"Easy",cal:470,protein:"36g",
   desc:"Baked salmon over quinoa with roasted vegetables.",
   ing:["3 salmon fillets","1 cup quinoa","4 cups mixed vegetables","2 tbsp olive oil","1 lemon","Dried herbs"],
   steps:["Cook quinoa; roast vegetables at 425°F 20 min.","Bake salmon at 400°F 12–14 min.","Divide quinoa, salmon and veg into 3 boxes.","Add lemon; refrigerate up to 3 days."],
   pair:"~470 cal · 36g protein"},
  {course:"main",cat:"mealprep",emoji:"🥗",title:"Greek Chicken Prep",it:"Mediterranean & lean",time:"40 min",serves:"4 boxes",level:"Easy",cal:420,protein:"40g",
   desc:"Lemon-oregano chicken with couscous, cucumber and tomato.",
   ing:["1.5 lb chicken breast","1.5 cups couscous or quinoa","2 cucumbers, 2 cups tomatoes","1/2 cup tzatziki","Olive oil","1 lemon, oregano"],
   steps:["Marinate and cook chicken to 165°F; slice.","Prepare couscous or quinoa.","Divide grain, chicken, cucumber and tomato into 4 boxes.","Pack tzatziki on the side; refrigerate up to 4 days."],
   pair:"~420 cal · 40g protein"},
  {course:"main",cat:"mealprep",emoji:"🌱",title:"Tofu Stir-Fry Boxes",it:"Plant-based & light",time:"35 min",serves:"4 boxes",level:"Easy",cal:390,protein:"22g",
   desc:"Crispy tofu and vegetables in a light soy-ginger glaze over rice.",
   ing:["14 oz extra-firm tofu","4 cups stir-fry vegetables","1.5 cups rice","3 tbsp soy sauce","1 tbsp honey or maple","Ginger, garlic, sesame oil"],
   steps:["Press and cube tofu; pan-fry until crisp.","Stir-fry vegetables, add tofu, soy, honey, ginger, garlic.","Cook rice.","Divide into 4 boxes; top with scallion. Refrigerate up to 4 days."],
   pair:"~390 cal · 22g protein"}
];

function daySeed(d=new Date()){return Math.floor(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())/86400000);}
function byCourse(c){return RECIPES.filter(r=>r.course===c);}
function pickForDate(course,d=new Date()){let l=byCourse(course);if(course==="main")l=l.filter(r=>r.cat!=="mealprep");return l[daySeed(d)%l.length];}
function menuForDate(d=new Date()){return {appetizer:pickForDate("appetizer",d),main:pickForDate("main",d),side:pickForDate("side",d),dessert:pickForDate("dessert",d)};}
function todaysMenu(){return menuForDate(new Date());}
function recipeForDate(d=new Date()){return pickForDate("main",d);}

export { CATS, COURSES, RECIPES, daySeed, byCourse, pickForDate, menuForDate, todaysMenu, recipeForDate };
