const CATS = {
  italian:   {label:"Italian",          color:"#7f8a52", emoji:"🍝"},
  steakhouse:{label:"Steakhouse",       color:"#a4592e", emoji:"🥩"},
  seafood:   {label:"Seafood",          color:"#3f7d8a", emoji:"🦐"},
  comfort:   {label:"Comfort & Healthy",color:"#9a7d3c", emoji:"🥗"},
  mealprep:  {label:"Meal Prep",        color:"#5d8a6a", emoji:"🥡"}
};

const RECIPES = [
  /* ---------- ITALIAN ---------- */
  {cat:"italian",emoji:"🍝",title:"Spaghetti Aglio e Olio",it:"Garlic & oil, the Roman way",time:"20 min",serves:"2",level:"Easy",
   desc:"Pantry magic — golden garlic, good olive oil, chili and parsley clinging to al dente spaghetti.",
   ing:["6 oz spaghetti","1/3 cup extra-virgin olive oil","5 cloves garlic, thinly sliced","1/2 tsp chili flakes","1/4 cup chopped parsley","1/2 cup pasta water (reserved)","Salt","Grated Parmesan (optional)"],
   steps:["Boil spaghetti in well-salted water until al dente; reserve 1/2 cup water before draining.","Warm olive oil over medium-low, add garlic and chili flakes, cook gently until garlic is pale gold.","Add a splash of pasta water to the oil to make a light sauce.","Toss in the pasta and parsley, adding more pasta water until silky.","Season, finish with Parmesan if you like, and serve right away."],
   pair:"A crisp Vermentino or Pinot Grigio."},
  {cat:"italian",emoji:"🍗",title:"Chicken Parmesan",it:"Pollo alla parmigiana",time:"45 min",serves:"2",level:"Medium",
   desc:"Crisp breaded cutlets under bubbling marinara and melted mozzarella.",
   ing:["2 chicken breasts, butterflied","1/2 cup flour","2 eggs, beaten","1 cup breadcrumbs","1/2 cup grated Parmesan","1.5 cups marinara","4 oz mozzarella","Olive oil","Salt, pepper, basil"],
   steps:["Pound chicken thin; season. Dredge in flour, then egg, then breadcrumbs mixed with half the Parmesan.","Pan-fry in olive oil 3–4 min per side until golden; transfer to a baking dish.","Heat oven to 425°F. Spoon marinara over each cutlet and top with mozzarella and remaining Parmesan.","Bake 12–15 min until cheese is bubbling and golden.","Finish with torn basil. Great over pasta or with a salad."],
   pair:"A medium Chianti or Sangiovese."},
  {cat:"italian",emoji:"🍚",title:"Mushroom Risotto",it:"Risotto ai funghi",time:"40 min",serves:"2",level:"Medium",
   desc:"Creamy, slow-stirred Arborio rice with earthy mushrooms and Parmesan.",
   ing:["1 cup Arborio rice","8 oz mushrooms, sliced","1 shallot, minced","4 cups warm stock","1/2 cup white wine","3 tbsp butter","1/3 cup grated Parmesan","Olive oil, salt, pepper, parsley"],
   steps:["Sauté mushrooms in olive oil until browned; set aside.","In the same pan, soften shallot in butter, add rice and toast 1 min.","Add wine, stir until absorbed. Add warm stock a ladle at a time, stirring, until each is absorbed (~18 min).","When rice is creamy and al dente, fold in mushrooms, Parmesan and a knob of butter.","Season, scatter parsley, and serve immediately."],
   pair:"A light Pinot Noir or Soave."},
  {cat:"italian",emoji:"🍅",title:"Penne alla Vodka",it:"Silky tomato-cream",time:"30 min",serves:"2",level:"Easy",
   desc:"Tomato, a splash of vodka, and cream come together into a luxe blush sauce.",
   ing:["6 oz penne","2 tbsp olive oil","2 cloves garlic, minced","1/2 tsp chili flakes","3 tbsp tomato paste","2 tbsp vodka","1/2 cup heavy cream","1/4 cup grated Parmesan","Salt, basil"],
   steps:["Boil penne in salted water until al dente; reserve some pasta water.","Soften garlic and chili in olive oil, stir in tomato paste and cook 2 min until deepened.","Add vodka, cook 1 min, then stir in cream until smooth.","Toss pasta into the sauce with a splash of pasta water and the Parmesan.","Season, finish with basil, and serve."],
   pair:"A chilled rosé or light red."},
  {cat:"italian",emoji:"🍕",title:"Margherita Flatbread",it:"Quick weeknight pizza",time:"25 min",serves:"2",level:"Easy",
   desc:"Blistered flatbread with tomato, fresh mozzarella and basil.",
   ing:["2 flatbreads or naan","1/2 cup crushed tomatoes","4 oz fresh mozzarella, torn","1 clove garlic","Olive oil","Fresh basil","Salt, pepper"],
   steps:["Heat oven to 450°F. Rub flatbreads with a cut garlic clove and a little olive oil.","Spread with tomatoes, season lightly, and dot with mozzarella.","Bake 8–10 min until cheese melts and edges crisp.","Finish with basil, a drizzle of olive oil and cracked pepper."],
   pair:"A simple Italian lager or Chianti."},
  {cat:"italian",emoji:"🍤",title:"Lemon Shrimp Linguine",it:"Linguine ai gamberi",time:"25 min",serves:"2",level:"Easy",
   desc:"Garlicky shrimp, lemon and white wine tangled through fresh linguine.",
   ing:["6 oz linguine","10 large shrimp, peeled","3 cloves garlic, minced","3 tbsp butter","1/4 cup white wine","1 lemon (juice + zest)","Chili flakes, parsley, salt"],
   steps:["Cook linguine until al dente; reserve pasta water.","Sauté garlic and chili in butter, add shrimp and cook 1–2 min per side until pink.","Add wine and lemon juice, simmer 1 min.","Toss in pasta with a splash of pasta water, lemon zest and parsley.","Season and serve hot."],
   pair:"A crisp Vermentino."},

  /* ---------- STEAKHOUSE ---------- */
  {cat:"steakhouse",emoji:"🥩",title:"Garlic Butter Ribeye",it:"The classic steakhouse sear",time:"25 min",serves:"2",level:"Medium",
   desc:"A deeply seared ribeye basted in garlic-herb butter — pure steakhouse.",
   ing:["2 ribeye steaks (1.25 in thick)","2 tbsp neutral oil","3 tbsp butter","3 cloves garlic, smashed","2 sprigs thyme & rosemary","Flaky salt, pepper"],
   steps:["Pat steaks very dry; season generously and let sit 30 min at room temp.","Sear in screaming-hot oil 3 min per side for a dark crust.","Lower heat, add butter, garlic and herbs; tilt the pan and baste 1–2 min.","Pull at 130–135°F for medium-rare and rest 8 min before slicing.","Spoon over the garlic butter and finish with flaky salt."],
   pair:"A bold Cabernet Sauvignon."},
  {cat:"steakhouse",emoji:"🔥",title:"Grilled Sirloin & Asparagus",it:"Bistecca con asparagi",time:"25 min",serves:"2",level:"Easy",
   desc:"Lean rosemary-garlic sirloin and charred asparagus, straight off the grill.",
   ing:["2 top sirloin steaks (6 oz)","1 tbsp olive oil","2 cloves garlic, smashed","2 sprigs rosemary","1 bunch asparagus","1/2 lemon","Salt, pepper"],
   steps:["Rub steaks with oil, garlic, salt and pepper; let sit while the grill heats to medium-high.","Grill steaks 3–4 min per side for medium-rare, rosemary on top.","Rest steaks 8 min; meanwhile toss asparagus in oil and grill 4–5 min until charred.","Squeeze lemon over the asparagus.","Slice steak across the grain and serve together."],
   pair:"A Chianti Classico."},
  {cat:"steakhouse",emoji:"🍷",title:"Filet Mignon, Red Wine Sauce",it:"Tender & elegant",time:"35 min",serves:"2",level:"Medium",
   desc:"Butter-basted filet with a glossy red wine pan reduction.",
   ing:["2 filet mignon (6–8 oz)","2 tbsp oil + 3 tbsp butter","2 cloves garlic","2 sprigs thyme","1/2 cup red wine","1/2 cup beef stock","Salt, pepper"],
   steps:["Season filets well. Sear in oil over high heat 3 min per side.","Add butter, garlic and thyme; baste 1–2 min, then rest steaks 8 min.","Pour off fat, add wine and stock to the pan and simmer until reduced by half.","Swirl in a knob of butter for shine.","Spoon sauce over the rested filets."],
   pair:"A Malbec or Bordeaux."},
  {cat:"steakhouse",emoji:"🌿",title:"NY Strip with Chimichurri",it:"Bright herb sauce",time:"25 min",serves:"2",level:"Easy",
   desc:"Charred strip steak cut by a punchy garlic-herb chimichurri.",
   ing:["2 NY strip steaks","Olive oil, salt, pepper","1 cup parsley, minced","2 cloves garlic, minced","2 tbsp red wine vinegar","1/3 cup olive oil","1/2 tsp chili flakes, oregano"],
   steps:["Stir together parsley, garlic, vinegar, olive oil, chili and oregano; season the chimichurri.","Season steaks and sear or grill 3–4 min per side for medium-rare.","Rest 8 min, then slice across the grain.","Spoon chimichurri generously over the top."],
   pair:"A Malbec or Tempranillo."},
  {cat:"steakhouse",emoji:"🍖",title:"Steakhouse Pork Chops",it:"With caramelized apples",time:"30 min",serves:"2",level:"Easy",
   desc:"Thick seared chops with sweet-tart skillet apples.",
   ing:["2 bone-in pork chops","2 tbsp oil + 2 tbsp butter","2 cloves garlic","2 sprigs thyme","1 apple, sliced","1 tbsp brown sugar","Salt, pepper"],
   steps:["Season chops; sear in oil 4 min per side until golden.","Add butter, garlic and thyme; baste, then rest the chops.","In the same pan, cook apple slices with brown sugar until caramelized.","Serve chops topped with the warm apples."],
   pair:"A fruity Zinfandel."},
  {cat:"steakhouse",emoji:"🥔",title:"Steak & Crispy Potatoes",it:"Bistecca e patate",time:"40 min",serves:"2",level:"Medium",
   desc:"Seared steak with golden, crispy smashed potatoes.",
   ing:["2 steaks of choice","1 lb baby potatoes","3 tbsp olive oil","3 tbsp butter","2 cloves garlic","Rosemary, salt, pepper"],
   steps:["Boil potatoes until tender, drain, then smash lightly. Roast at 450°F in olive oil 25 min until crispy.","Season and sear steaks 3–4 min per side; baste with butter, garlic and rosemary.","Rest steaks 8 min.","Serve with the crispy potatoes and a spoonful of the garlic butter."],
   pair:"A Cabernet or Syrah."},

  /* ---------- SEAFOOD ---------- */
  {cat:"seafood",emoji:"🐟",title:"Pan-Seared Salmon",it:"Crispy skin, lemon butter",time:"20 min",serves:"2",level:"Easy",
   desc:"Crisp-skinned salmon finished with a quick lemon-butter pan sauce.",
   ing:["2 salmon fillets","1 tbsp oil","2 tbsp butter","1 clove garlic","1/2 lemon","Salt, pepper, dill"],
   steps:["Pat salmon dry, season. Sear skin-side down in oil 4–5 min until crisp.","Flip and cook 2–3 min more.","Lower heat, add butter and garlic, squeeze in lemon and baste.","Finish with dill and spoon over the lemon butter."],
   pair:"A Chardonnay or Pinot Noir."},
  {cat:"seafood",emoji:"🍤",title:"Shrimp Scampi",it:"Garlic butter & wine",time:"20 min",serves:"2",level:"Easy",
   desc:"Plump shrimp in a garlicky white wine butter — serve over pasta or with bread.",
   ing:["1 lb shrimp, peeled","4 tbsp butter","4 cloves garlic, minced","1/3 cup white wine","1/2 lemon","Chili flakes, parsley, salt"],
   steps:["Melt 2 tbsp butter, sauté garlic and chili 30 sec.","Add shrimp, cook 1–2 min per side until pink; remove.","Add wine and lemon, simmer 2 min, then swirl in remaining butter.","Return shrimp, toss with parsley and serve."],
   pair:"A crisp Sauvignon Blanc."},
  {cat:"seafood",emoji:"🧈",title:"Seared Scallops, Pea Purée",it:"Restaurant at home",time:"25 min",serves:"2",level:"Medium",
   desc:"Golden-crusted scallops over a silky pea purée with lemon butter.",
   ing:["6 large scallops","1.5 cups peas","2 tbsp cream","3 tbsp butter","1 tbsp olive oil","1/2 lemon","Salt, pepper, mint"],
   steps:["Boil peas 3 min, blend with cream, 1 tbsp butter, salt and pepper until smooth.","Pat scallops very dry and season. Sear in hot oil 1.5–2 min per side until golden.","Add butter and lemon, baste briefly.","Spoon pea purée onto plates, top with scallops and the lemon butter; garnish with mint."],
   pair:"A Chablis or sparkling wine."},
  {cat:"seafood",emoji:"🌮",title:"Blackened Fish Tacos",it:"With lime slaw",time:"25 min",serves:"2",level:"Easy",
   desc:"Spiced fish in warm tortillas with crunchy lime slaw.",
   ing:["2 white fish fillets","1 tbsp blackening spice","2 cups shredded cabbage","2 tbsp mayo or yogurt","1 lime","6 small tortillas","Cilantro, oil, salt"],
   steps:["Toss cabbage with mayo, lime juice, cilantro and salt for the slaw.","Coat fish in blackening spice; sear in oil 3 min per side until charred and flaky.","Warm the tortillas.","Flake fish into tortillas, top with slaw and an extra squeeze of lime."],
   pair:"A Mexican lager or margarita."},
  {cat:"seafood",emoji:"🍋",title:"Lemon Herb Baked Cod",it:"Light & flaky",time:"25 min",serves:"2",level:"Easy",
   desc:"Tender cod baked with lemon, garlic and herbs — barely any effort.",
   ing:["2 cod fillets","2 tbsp butter, melted","2 cloves garlic, minced","1 lemon","2 tbsp parsley","Salt, pepper, paprika"],
   steps:["Heat oven to 400°F. Place cod in a baking dish.","Mix melted butter, garlic, lemon juice and parsley; pour over the fish.","Season with salt, pepper and a little paprika.","Bake 12–15 min until the fish flakes easily. Spoon over the pan juices."],
   pair:"A dry Riesling or Albariño."},
  {cat:"seafood",emoji:"🍣",title:"Tuna Poke Bowl",it:"No-cook & fresh",time:"15 min",serves:"2",level:"Easy",
   desc:"Marinated raw tuna over rice with avocado, cucumber and sesame.",
   ing:["8 oz sushi-grade tuna, cubed","2 tbsp soy sauce","1 tsp sesame oil","1 tsp rice vinegar","2 cups cooked rice","1 avocado","1/2 cucumber","Sesame seeds, scallion"],
   steps:["Toss tuna with soy sauce, sesame oil and rice vinegar; chill 10 min.","Divide rice between bowls.","Top with tuna, sliced avocado and cucumber.","Finish with sesame seeds and scallion."],
   pair:"A dry sparkling wine or sake."},

  /* ---------- COMFORT & HEALTHY ---------- */
  {cat:"comfort",emoji:"🍗",title:"Sheet-Pan Chicken & Veg",it:"One pan, no fuss",time:"40 min",serves:"2",level:"Easy",
   desc:"Juicy chicken thighs roasted with vegetables — dinner on a single tray.",
   ing:["4 chicken thighs","2 cups broccoli & peppers","1 cup baby potatoes","2 tbsp olive oil","2 cloves garlic","Paprika, oregano, salt, pepper","1/2 lemon"],
   steps:["Heat oven to 425°F. Toss vegetables and potatoes in oil, garlic and seasoning on a sheet pan.","Nestle in seasoned chicken thighs, skin-side up.","Roast 30–35 min until chicken is golden and cooked through.","Squeeze lemon over everything before serving."],
   pair:"A light unoaked white."},
  {cat:"comfort",emoji:"🌶️",title:"Turkey & White Bean Chili",it:"Lean & cozy",time:"40 min",serves:"3–4",level:"Easy",
   desc:"A lighter chili that's still rich, hearty and freezer-friendly.",
   ing:["1 lb ground turkey","1 onion, diced","2 cloves garlic","1 can white beans","1 can diced tomatoes","2 cups stock","2 tbsp chili powder, cumin","Salt, pepper"],
   steps:["Brown turkey with onion and garlic.","Stir in chili powder and cumin, cook 1 min.","Add beans, tomatoes and stock; simmer 25 min until thickened.","Season and serve with your favorite toppings."],
   pair:"A cold lager or Zinfandel."},
  {cat:"comfort",emoji:"🥗",title:"Greek Chicken Bowls",it:"Bright & balanced",time:"30 min",serves:"2",level:"Easy",
   desc:"Lemon-oregano chicken over rice with cucumber, tomato and tzatziki.",
   ing:["2 chicken breasts, cubed","2 tbsp olive oil","1 lemon","1 tsp oregano","2 cups cooked rice or quinoa","1 cucumber, 1 cup tomatoes","1/2 cup tzatziki","Feta, salt, pepper"],
   steps:["Toss chicken with olive oil, lemon, oregano, salt and pepper; sear 6–8 min until cooked.","Divide rice or quinoa between bowls.","Top with chicken, chopped cucumber and tomato.","Add a dollop of tzatziki and crumbled feta."],
   pair:"A crisp Assyrtiko or rosé."},
  {cat:"comfort",emoji:"🍯",title:"Honey Garlic Salmon Bowl",it:"Sweet & savory",time:"25 min",serves:"2",level:"Easy",
   desc:"Glazed salmon over rice and greens — fast, healthy and crave-worthy.",
   ing:["2 salmon fillets, cubed","2 tbsp honey","2 tbsp soy sauce","2 cloves garlic","1 tsp ginger","2 cups cooked rice","2 cups greens or edamame","Sesame, scallion"],
   steps:["Whisk honey, soy, garlic and ginger.","Sear salmon cubes 2 min, add the glaze and toss until sticky.","Serve over rice with greens or edamame.","Finish with sesame seeds and scallion."],
   pair:"A off-dry Riesling."},
  {cat:"comfort",emoji:"🍲",title:"Hearty Minestrone",it:"Garden vegetable soup",time:"40 min",serves:"3–4",level:"Easy",
   desc:"A big pot of vegetables, beans and pasta in a savory tomato broth.",
   ing:["2 tbsp olive oil","1 onion, 2 carrots, 2 celery, diced","2 cloves garlic","1 can diced tomatoes","4 cups stock","1 can cannellini beans","1/2 cup small pasta","Parmesan rind, basil"],
   steps:["Soften onion, carrot, celery and garlic in olive oil.","Add tomatoes, stock and Parmesan rind; simmer 15 min.","Add beans and pasta; cook until pasta is tender.","Season and finish with basil and grated Parmesan."],
   pair:"A light Italian red or just good bread."},
  {cat:"comfort",emoji:"🍋",title:"Roast Lemon Chicken Thighs",it:"Crispy & golden",time:"45 min",serves:"2",level:"Easy",
   desc:"Crispy-skinned thighs roasted with lemon and garlic — weeknight comfort.",
   ing:["4–6 chicken thighs","2 tbsp olive oil","4 cloves garlic","1 lemon, sliced","2 sprigs rosemary","Salt, pepper"],
   steps:["Heat oven to 425°F. Pat thighs dry and season well.","Arrange in a dish with garlic, lemon slices and rosemary; drizzle with oil.","Roast 35–40 min until skin is crisp and deeply golden.","Spoon over the pan juices and serve."],
   pair:"A Chardonnay or light red."},

  /* ---------- MEAL PREP (weight loss) ---------- */
  {cat:"mealprep",emoji:"🍗",title:"Chicken & Rice Prep Bowls",it:"The classic high-protein box",time:"45 min",serves:"4 boxes",level:"Easy",cal:430,protein:"42g",
   desc:"Lean grilled chicken, fluffy rice and roasted broccoli — four ready-to-grab high-protein boxes.",
   ing:["1.5 lb chicken breast","1.5 cups rice (dry)","4 cups broccoli florets","2 tbsp olive oil","2 cloves garlic, minced","1 tsp paprika & garlic powder","1/2 lemon","Salt, pepper"],
   steps:["Season chicken with paprika, garlic powder, salt and pepper. Cook the rice.","Sear or bake chicken until 165°F, then rest and slice.","Roast broccoli in olive oil and garlic at 425°F for 18 min.","Divide rice, chicken and broccoli into 4 containers; squeeze lemon over the top.","Cool fully, lid, and refrigerate up to 4 days."],
   pair:"~430 cal · high protein · meal-prep friendly"},
  {cat:"mealprep",emoji:"🌮",title:"Turkey Taco Prep Bowls",it:"Lean & punchy",time:"35 min",serves:"4 boxes",level:"Easy",cal:410,protein:"38g",
   desc:"Lean turkey taco meat over rice and beans with peppers — big flavor, controlled calories.",
   ing:["1.25 lb 93% lean ground turkey","1 onion + 2 peppers, diced","1 can black beans, rinsed","2 tbsp taco seasoning","1.5 cups rice (dry)","1 cup corn","Lime, cilantro, salt"],
   steps:["Cook rice. Brown turkey with onion and peppers.","Stir in taco seasoning, beans and corn; simmer 5 min.","Divide rice and turkey mixture into 4 containers.","Top with lime and cilantro; cool and refrigerate up to 4 days."],
   pair:"~410 cal · 38g protein · 4 servings"},
  {cat:"mealprep",emoji:"🥚",title:"Egg & Veggie Cups",it:"Grab-and-go breakfast",time:"30 min",serves:"6 cups",level:"Easy",cal:120,protein:"11g",
   desc:"Baked egg muffins loaded with veggies — make a batch and breakfast is solved all week.",
   ing:["8 eggs","1 cup spinach, chopped","1/2 cup diced peppers","1/4 cup diced onion","1/3 cup feta or cheddar","Salt, pepper","Cooking spray"],
   steps:["Heat oven to 375°F and grease a muffin tin.","Whisk eggs with salt and pepper; stir in vegetables and cheese.","Pour into 6 muffin cups.","Bake 18–20 min until set. Cool and refrigerate up to 4 days; reheat in seconds."],
   pair:"~120 cal each · 11g protein · low carb"},
  {cat:"mealprep",emoji:"🐟",title:"Salmon & Quinoa Boxes",it:"Omega-3 powerhouse",time:"35 min",serves:"3 boxes",level:"Easy",cal:470,protein:"36g",
   desc:"Baked salmon over quinoa with roasted vegetables — light, filling and anti-inflammatory.",
   ing:["3 salmon fillets","1 cup quinoa (dry)","4 cups mixed vegetables","2 tbsp olive oil","1 lemon","1 tsp dried herbs","Salt, pepper"],
   steps:["Cook quinoa. Roast vegetables in olive oil at 425°F for 20 min.","Season salmon and bake at 400°F for 12–14 min until flaky.","Divide quinoa, salmon and vegetables into 3 containers.","Add lemon; cool and refrigerate up to 3 days."],
   pair:"~470 cal · 36g protein · high omega-3"},
  {cat:"mealprep",emoji:"🥗",title:"Greek Chicken Prep",it:"Mediterranean & lean",time:"40 min",serves:"4 boxes",level:"Easy",cal:420,protein:"40g",
   desc:"Lemon-oregano chicken with couscous, cucumber and tomato — bright Mediterranean boxes.",
   ing:["1.5 lb chicken breast","1.5 cups couscous or quinoa","2 cucumbers, 2 cups tomatoes","1/2 cup tzatziki","2 tbsp olive oil","1 lemon, 1 tsp oregano","Salt, pepper"],
   steps:["Marinate chicken in olive oil, lemon, oregano, salt and pepper; cook until 165°F and slice.","Prepare couscous or quinoa.","Divide grain, chicken, chopped cucumber and tomato into 4 boxes.","Pack tzatziki on the side; refrigerate up to 4 days."],
   pair:"~420 cal · 40g protein · Mediterranean"},
  {cat:"mealprep",emoji:"🌱",title:"Tofu Stir-Fry Boxes",it:"Plant-based & light",time:"35 min",serves:"4 boxes",level:"Easy",cal:390,protein:"22g",
   desc:"Crispy tofu and vegetables in a light soy-ginger glaze over rice — vegan and satisfying.",
   ing:["14 oz extra-firm tofu, cubed","4 cups stir-fry vegetables","1.5 cups rice (dry)","3 tbsp soy sauce","1 tbsp honey or maple","1 tsp ginger + garlic","1 tbsp sesame oil, scallion"],
   steps:["Press and cube tofu; pan-fry in sesame oil until crisp on all sides.","Stir-fry vegetables, then add tofu, soy, honey, ginger and garlic; toss until glazed.","Cook the rice.","Divide rice and stir-fry into 4 boxes; top with scallion. Refrigerate up to 4 days."],
   pair:"~390 cal · 22g protein · vegan"}
];

function daySeed(d=new Date()){return Math.floor(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())/86400000);}
function recipeForDate(d=new Date()){return RECIPES[daySeed(d)%RECIPES.length];}

export { CATS, RECIPES, daySeed, recipeForDate };
